// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6RxFLNaL4F5mMYlbOcjEcYJbi8aXK8w',
    appId: '1:1094286022489:web:afb7c611e910bf21275e48',
    messagingSenderId: '1094286022489',
    projectId: 'chur-103fc',
    authDomain: 'chur-103fc.firebaseapp.com',
    storageBucket: 'chur-103fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR-fcs9mZTCqnL-nY_tEAla_oCrj7HBbQ',
    appId: '1:1094286022489:android:7f8b9cdbc5e16787275e48',
    messagingSenderId: '1094286022489',
    projectId: 'chur-103fc',
    storageBucket: 'chur-103fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVGOOfZiHEFSDOXmqjE-R_Hbzfm9T8Rv4',
    appId: '1:1094286022489:ios:01158600bdef0c7b275e48',
    messagingSenderId: '1094286022489',
    projectId: 'chur-103fc',
    storageBucket: 'chur-103fc.appspot.com',
    iosClientId: '1094286022489-9q4rn2u7jgvnmeoolbj20btpla4euomb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVGOOfZiHEFSDOXmqjE-R_Hbzfm9T8Rv4',
    appId: '1:1094286022489:ios:a09f15c316e339ee275e48',
    messagingSenderId: '1094286022489',
    projectId: 'chur-103fc',
    storageBucket: 'chur-103fc.appspot.com',
    iosClientId: '1094286022489-l69v0m1toh22971ovgq3p2t8igoouv4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chur.RunnerTests',
  );
}
